[package]
name = "conduit-dataplane"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
conduit-core = { path = "../conduit-core" }
conduit-config = { path = "../conduit-config" }
conduit-events = { path = "../conduit-events" }
conduit-metrics = { path = "../conduit-metrics" }
conduit-proto = { path = "../conduit-proto" }
hickory-proto = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
arc-swap = { workspace = true }

[dev-dependencies]
conduit-config = { path = "../conduit-config" }
