[package]
name = "conduit-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
conduit-proto = { path = "../conduit-proto" }
conduit-config = { path = "../conduit-config" }
conduit-core = { path = "../conduit-core" }
conduit-metrics = { path = "../conduit-metrics" }
anyhow = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
conduit-config = { path = "../conduit-config" }
conduit-core = { path = "../conduit-core" }
conduit-metrics = { path = "../conduit-metrics" }
hickory-proto = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
