[package]
name = "conduit"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "conduit"
path = "src/main.rs"

[dependencies]
conduit-proto = { path = "../conduit-proto" }
conduit-config = { path = "../conduit-config" }
conduit-core = { path = "../conduit-core" }
conduit-api = { path = "../conduit-api" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
