[package]
name = "conduit-script"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[features]
test-util = []

[[bench]]
name = "thread_local_runtime"
harness = false
required-features = ["test-util"]

[dependencies]
conduit-proto = { path = "../conduit-proto" }
conduit-events = { path = "../conduit-events" }
conduit-metrics = { path = "../conduit-metrics" }
rhai = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
conduit-config = { path = "../conduit-config" }
tempfile = "3"
