[package]
name = "conduit-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
conduit-proto = { path = "../conduit-proto" }
conduit-config = { path = "../conduit-config" }
conduit-observation = { path = "../conduit-observation" }
arc-swap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
hickory-proto = { workspace = true }

[dev-dependencies]
conduit-config = { path = "../conduit-config" }
