[package]
name = "conduit-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
conduit-proto = { path = "../conduit-proto" }
conduit-config = { path = "../conduit-config" }
conduit-events = { path = "../conduit-events" }
conduit-script = { path = "../conduit-script" }
conduit-metrics = { path = "../conduit-metrics" }
arc-swap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tracing = { workspace = true }
hickory-proto = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
conduit-config = { path = "../conduit-config" }
hickory-proto = { workspace = true }
