[package]
name = "conduitctl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "conduitctl"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive", "env"] }
conduit-config = { path = "../conduit-config" }
conduit-core = { path = "../conduit-core" }
conduit-proto = { path = "../conduit-proto" }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
serde_json = { workspace = true }
